<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zf2mail\Module'                        => __DIR__ . '/Module.php',
    'Zf2mail\Controller\EmailersController' => __DIR__ . '/src/Zf2mail/Controller/EmailersController.php',
);
